### ISSUE TITLE
Роуты 🌍

### ISSUE THREAD

**Issue by mintolime** [ConstantineEpifanov/book-it-coworking-frontend#5]
# Install
```
npm i react-router
```
---- 

## Подготовьте необходимые маршруты:

- [ ] по роуту `/` отображается страница главная страница « »;
- [ ]  по роуту `/profile` отображается страница с профилем пользователя(личный кабинет);
- [ ]  по роутам `/signin` и `/signup` отображаются страницы авторизации и регистрации.
- [ ]  страница с коворкингами `/сo-workings`
- [ ]   страница отдельного коворкинга `/сo-workings/id`
- [ ]   мои бронирования `/bookings`
- [x]  страница с контактами `/contacts`

[Ссылка на документацию](https://reactrouter.com/en/main/start/tutorial)

**Comment by mintolime** [comment]
Это базовые роуты, далее будем добавлять. 
Нужно еще продумать , какие роуты будем защищать от неавторизованного пользователя..

**Comment by ConstantineEpifanov** [comment]
Какие у нас сейчас есть страницы:

Главная
Коворкинги - список коворкингов с фильтром и кнопкой "Еще"
Правила и вопросы
Контакты и инфа о нас
404
Личный кабинет (У каждого пункта профиля наверно также надо сделать отдельную страницу?)


Также у каждого коворкинга своя страница?
Бронирование
Оплата

**Comment by mintolime** [comment]
наверное страница оплаты отдельная страница . а личный кабинет может как меню...?
